<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LotroPresence.Tests</AssemblyName>
    <RootNamespace>LotroPresence.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../bridge/LotroPresence.Bridge/LotroPresence.Bridge.csproj" />
  </ItemGroup>

</Project>
