<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LotroPresence</AssemblyName>
    <RootNamespace>LotroPresence.Bridge</RootNamespace>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.default.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="config.example.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
